### ISSUE TITLE
Infinity eggs from dispenser

### ISSUE THREAD

**Issue by SkyGopnik** [foss-mc/SSSpigot#14]
Discord
SkyGopnik#8685

Observed behavior on SSSpigot
Infinity eggs from dispenser

Observed behavior on Patina (if known)
We were previously running Patina without any problems.

Installed plugins
![image](https://user-images.githubusercontent.com/26293210/131475155-ce1d5877-5d94-4c8f-91af-cca1fe746877.png)

Plugins with a * at the end are our closed-soruce plugins, which do NOT mess with anything world-related

Version
![image](https://user-images.githubusercontent.com/26293210/131475122-c3fcbc67-adfe-4494-a88d-74dd82cc50d8.png)

https://youtu.be/-MtmOT5wQLQ

**Comment by foss-mc** [comment]
I can't reproduce it

**Comment by SkyGopnik** [comment]
Our bug, sorry)
